Repository JiscSD/octopus, pull requests merged in 2022-07, with the labels that each got.

#180 OCT-236 Token issue following email verification
  ui/src/pages/verify.tsx
Labels: bug, ui

#184 Overlapping issue with the dropdown profile menu and the linked publication visualisation section - UI
  ui/src/components/Nav/Desktop/index.tsx
Labels: ui

#192 Add link to author guide on create publication page and change position of the 'Co-author' step within the publication build process
  ui/src/components/Publication/Creation/CoAuthor.tsx
  ui/src/pages/create.tsx
  ui/src/pages/publications/[id]/edit.tsx
Labels: ui

#189 Remove two licence options and change the licence copy - UI
  api/prisma/migrations/20220707145753_remove_copyright_licence_types/migration.sql
  api/prisma/schema.prisma
  api/prisma/seeds/publicationsDevSeedData.ts
  api/src/components/publication/__tests__/updatePublication.test.ts
  api/src/components/publication/schema/create.ts
  api/src/components/publication/schema/update.ts
  ui/src/components/Publication/Creation/KeyInformation.tsx
  ui/src/config/values.ts
Labels: api, ui

#182 Allow users to add an 'Affiliated Organisations' and/or 'Funders' statement if no organisation has been added - UI
  ui/src/components/RORForm/index.tsx
  ui/src/pages/create.tsx
  ui/src/pages/publications/[id]/index.tsx
Labels: ui

#177 Oct-221 Behaviour of peer review link for non-logged in users
  ui/src/components/Alert/index.tsx
  ui/src/components/Publication/SidebarCard/Actions/index.tsx
  ui/src/components/Publication/SidebarCard/General/index.tsx
Labels: Fix, ui

#193 OCT-233 Co-author fixes
  api/src/components/coauthor/controller.ts
  ui/src/components/Publication/Creation/CoAuthor.tsx
  ui/src/layouts/InformationLanding.tsx
  ui/src/layouts/index.ts
  ui/src/lib/helpers.tsx
  ui/src/lib/types.ts
  ui/src/pages/author-link.tsx
  ui/src/pages/verify.tsx
Labels: bug, api, ui

#187 OCT-247 - Ethical Statement blocking publication
  api/prisma/migrations/20220706145818_update_ethical_statement/migration.sql
  api/prisma/schema.prisma
  api/prisma/seeds/publications.ts
  api/src/components/publication/schema/create.ts
  api/src/components/publication/schema/update.ts
  api/src/lib/interface.ts
  ui/src/components/Publication/Creation/DataStatements.tsx
  ui/src/components/Publication/Creation/Review.tsx
  ui/src/components/Publication/SearchResult/index.tsx
  ui/src/lib/interfaces.ts
  ui/src/lib/types.ts
  ui/src/pages/publications/[id]/index.tsx
  ui/src/pages/search.tsx
Labels: bug, api, ui

#194 OCT-240 Data permissions statement blocking publication
  ui/src/components/Publication/Creation/DataStatements.tsx
  ui/src/components/Publication/Creation/LinkedPublications.tsx
  ui/src/components/Publication/Creation/Review.tsx
  ui/src/config/values.ts
  ui/src/layouts/BuildPublication.tsx
  ui/src/pages/about.tsx
  ui/src/pages/index.tsx
  ui/src/stores/publicationCreation.ts
Labels: bug, ui

#199 Amendments to banner & footer to make the help email more prominent - UI (OCT-
  ui/src/components/Banner/index.tsx
  ui/src/components/Footer/index.tsx
  ui/src/components/Header/index.tsx
Labels: ui

#202 Fix affiliations bug - UI
  ui/src/pages/publications/[id]/edit.tsx
Labels: bug

#205 OCT-260 404 errors on publication creation
  api/src/components/publication/__tests__/updatePublication.test.ts
  api/src/components/publication/controller.ts
  api/src/lib/helpers.ts
Labels: bug, api

#206 Conflict of interest - 'No' value consistently not being retained - BUG - (OCT-263)
  api/prisma/migrations/20220720091606_conflict_of_interest_bug_fix/migration.sql
  api/prisma/schema.prisma
  ui/src/components/Publication/Creation/ConflictOfInterest.tsx
  ui/src/components/Publication/Creation/Review.tsx
  ui/src/layouts/BuildPublication.tsx
  ui/src/lib/interfaces.ts
  ui/src/lib/types.ts
  ui/src/pages/publications/[id]/edit.tsx
  ui/src/stores/publicationCreation.ts
Labels: bug
