Repository JiscSD/octopus, pull requests merged in 2022-08, with the labels that each got.

#210 Data access - 'other' field not being retained - BUG - (OCT-264)
  ui/src/components/Publication/Creation/DataStatements.tsx
  ui/src/lib/types.ts
Labels: bug

#209 OCT-262 - improve error handling for coauthor linking
  ui/src/lib/types.ts
  ui/src/pages/author-link.tsx
Labels: bug, ui

#212 Broken co-author link - (OCT-295) - BUG
  ui/src/pages/publications/[id]/index.tsx
Labels: bug

#211 Make buttons more prominent (OCT-243) - UI
  ui/src/components/Button/index.tsx
  ui/src/components/Publication/Creation/CoAuthor.tsx
  ui/src/components/RORForm/index.tsx
  ui/src/layouts/BuildPublication.tsx
Labels: ui

#220 Write a linked publication / review - OCT-200 (UI)
  ui/src/components/Publication/SidebarCard/Actions/index.tsx
  ui/src/lib/helpers.tsx
Labels: ui

#226 Fix OCT-200 bug where the linked publication buttons aren't displaying when a user views their own publication
  ui/src/components/Publication/SidebarCard/Actions/index.tsx
Labels: bug

#225 OCT-324
  ui/src/components/TextEditor/index.tsx
  ui/src/config/values.ts
  ui/src/styles/globals.css
Labels: bug, ui
