Repository JiscSD/octopus, pull requests merged in 2022-06, with the labels that each got.

#166 OCT-issue-149
  ui/package.json
  ui/src/components/Alert/index.tsx
  ui/src/components/Publication/Creation/CoAuthorEntry/index.tsx
  ui/src/components/Publication/Creation/MainText.tsx
  ui/src/components/Publication/SidebarCard/Actions/index.tsx
  ui/src/components/Publication/SidebarCard/Ratings/index.tsx
  ui/src/config/urls.ts
  ui/src/lib/api.ts
  ui/src/pages/index.tsx
  ui/src/pages/publications/[id]/index.tsx
  ui/src/stores/auth.ts
  ui/src/stores/globals.ts
  ui/src/stores/preferences.ts
  ui/src/stores/publicationCreation.ts
  ui/src/stores/toast.ts
Labels: Fix, ui

#162 Addition of several static pages - UI
  ui/src/components/Faq/Sidebar/index.tsx
  ui/src/components/Footer/index.tsx
  ui/src/components/Header/index.tsx
  ui/src/components/SearchToggle/Desktop/index.tsx
  ui/src/config/urls.ts
  ui/src/pages/about.tsx
  ui/src/pages/author-guide.tsx
  ui/src/pages/faq.tsx
  ui/src/pages/get-involved.tsx
  ui/src/pages/index.tsx
  ui/src/pages/octopus-aims.tsx
  ui/src/pages/privacy.tsx
  ui/src/pages/publications/[id]/index.tsx
  ui/src/pages/user-terms.tsx
Labels: ui

#168 OCT-issue-151
  ui/src/pages/search.tsx
Labels: Fix, ui

#159 Create an Affiliated Organisations field - API & UI (+ URL error within the ROR field bug fix)
  api/package-lock.json
  api/prisma/migrations/20220623101034_init/migration.sql
  api/prisma/schema.prisma
  api/prisma/seeds/publications.ts
  api/serverless.yml
  api/src/components/affiliations/__tests__/createAffiliation.test.ts
  api/src/components/affiliations/__tests__/deleteAffiliation.test.ts
  api/src/components/affiliations/controller.ts
  api/src/components/affiliations/routes.ts
  api/src/components/affiliations/schema/create.ts
  api/src/components/affiliations/schema/index.ts
  api/src/components/affiliations/service.ts
  api/src/components/publication/schema/create.ts
  api/src/components/publication/schema/update.ts
  api/src/components/publication/service.ts
  api/src/lib/interface.ts
  ui/src/components/Publication/Creation/Funders.tsx
  ui/src/components/Publication/Creation/KeyInformation.tsx
  ui/src/components/RORForm/index.tsx
  ui/src/components/index.tsx
  ui/src/layouts/BuildPublication.tsx
  ui/src/lib/interfaces.ts
  ui/src/lib/types.ts
  ui/src/pages/publications/[id]/index.tsx
  ui/src/stores/publicationCreation.ts
Labels: api, ui

#160 OCT-216 Publication visualisation
  api/prisma/seeds/publications.ts
  api/serverless.yml
  api/src/components/publication/__tests__/getPublicationLinks.ts
  api/src/components/publication/controller.ts
  api/src/components/publication/routes.ts
  api/src/components/publication/service.ts
  api/src/lib/interface.ts
  api/thunder-tests/thunderclient.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/Link/index.tsx
  ui/src/components/Publication/Visulization/index.tsx
  ui/src/components/index.tsx
  ui/src/layouts/Publication.tsx
  ui/src/lib/helpers.tsx
  ui/src/lib/interfaces.ts
  ui/src/pages/publications/[id]/index.tsx
Labels: enhancement, api, ui

#165 Update DOI with publication data
  api/.env.example
  api/.gitignore
  api/doi_example.json
  api/prisma/migrations/20220623110055_init/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed.ts
  api/prisma/seeds/problems.ts
  api/prisma/seeds/publications.ts
  api/prisma/seeds/publicationsDevSeedData.ts
  api/prisma/seeds/users.ts
  api/prisma/seeds/usersDevSeedData.ts
  api/src/components/bookmark/__tests__/createBookmark.test.ts
  api/src/components/bookmark/__tests__/getAllBookmarks.test.ts
  api/src/components/bookmark/__tests__/getBookmark.test.ts
  api/src/components/bookmark/__tests__/removeBookmark.test.ts
  api/src/components/coauthor/__tests__/createCoAuthor.test.ts
  api/src/components/coauthor/__tests__/deleteCoAuthor.test.ts
  api/src/components/coauthor/__tests__/linkCoAuthor.test.ts
  api/src/components/coauthor/__tests__/updateCoAuthor.test.ts
  api/src/components/flag/__tests__/createFlag.test.ts
  api/src/components/flag/__tests__/createFlagComment.test.ts
  api/src/components/flag/__tests__/resolveFlag.test.ts
  api/src/components/funder/__tests__/createFunder.test.ts
  api/src/components/funder/__tests__/deleteFunder.test.ts
  api/src/components/link/__tests__/createLink.ts
  api/src/components/link/__tests__/deleteLink.ts
  api/src/components/publication/__tests__/createPublication.test.ts
  api/src/components/publication/__tests__/deletePublication.test.ts
  api/src/components/publication/__tests__/getPublication.test.ts
  api/src/components/publication/__tests__/updatePublication.test.ts
  api/src/components/publication/__tests__/updateStatus.test.ts
  api/src/components/publication/controller.ts
  api/src/components/publication/service.ts
  api/src/components/rating/__tests__/createRating.ts
  api/src/components/rating/__tests__/getRating.ts
  api/src/components/user/__tests__/getUser.test.ts
  api/src/components/user/__tests__/getUserPublications.test.ts
  api/src/components/verification/__tests__/confirmCode.test.ts
  api/src/components/verification/__tests__/requestCode.test.ts
  api/src/lib/helpers.ts
  api/src/lib/interface.ts
  api/src/lib/testUtils.ts
  ui/src/components/Publication/Creation/CoAuthor.tsx
  ui/src/components/Publication/Creation/Review.tsx
  ui/src/components/Publication/SidebarCard/General/index.tsx
  ui/src/layouts/BuildPublication.tsx
Labels: api, ui

#172 OCT-218 Change Browser Tab Text
  ui/src/config/urls.ts
  ui/src/pages/login.tsx
Labels: Fix, ui

#175 OCT-224 Global change - Publication type names
  README.md
  ui/src/components/Publication/Creation/LinkedPublications.tsx
  ui/src/components/Publication/Creation/ResearchProcess.tsx
  ui/src/components/VisualPublicationFlow/index.tsx
  ui/src/config/values.ts
  ui/src/lib/helpers.tsx
  ui/src/pages/about.tsx
  ui/src/pages/author-guide.tsx
  ui/src/pages/create.tsx
  ui/src/pages/faq.tsx
  ui/src/pages/octopus-aims.tsx
  ui/src/pages/publications/[id]/index.tsx
  ui/src/pages/user-terms.tsx
Labels: Fix, ui
