Repository JiscSD/octopus, pull requests merged in 2022-03, with the labels that each got.

#88 lots of stuff...
  api/prisma/migrations/20220308173743_adding_education_and_employment_to_users/migration.sql
  api/prisma/migrations/20220308173840_adding_education/migration.sql
  api/prisma/schema.prisma
  api/src/components/authorization/controller.ts
  api/src/components/user/service.ts
  api/src/lib/interface.ts
  ui/package.json
  ui/public/images/logo-ukri.old.png
  ui/public/images/logo-ukri.png
  ui/src/components/Header/Nav/index.tsx
  ui/src/components/Header/SurveyAlert/index.tsx
  ui/src/components/Header/index.tsx
  ui/src/components/Publication/Creation/StepFive.tsx
  ui/src/components/Publication/Creation/StepOne.tsx
  ui/src/components/Publication/Creation/StepThree.tsx
  ui/src/components/index.tsx
  ui/src/config/urls.ts
  ui/src/layouts/BuildPublication.tsx
  ui/src/lib/api.ts
  ui/src/pages/accessibility.tsx
  ui/src/pages/account.tsx
  ui/src/pages/authors/[id]/index.tsx
  ui/src/pages/browse.tsx
  ui/src/pages/create.tsx
  ui/src/pages/documentation.tsx
  ui/src/pages/faq.tsx
  ui/src/pages/index.tsx
  ui/src/pages/privacy.tsx
  ui/src/pages/publications/[id]/edit.tsx
  ui/src/pages/publications/[id]/index.tsx
  ui/src/pages/search.tsx
  ui/src/pages/terms.tsx
  ui/src/templates/Error.tsx
Labels: enhancement

#90 Remove first name from publication page
  ui/src/pages/publications/[id]/index.tsx
Labels: bug

#94 Added employment & education history to public profile
  api/src/components/user/service.ts
  ui/src/components/Avatar/index.tsx
  ui/src/components/Users/HistoryTable/index.tsx
  ui/src/components/Users/SearchResult/index.tsx
  ui/src/components/index.tsx
  ui/src/lib/interfaces.ts
  ui/src/pages/authors/[id]/index.tsx
  ui/src/pages/search.tsx
Labels: enhancement

#96 Updated search result page filtering to align with api (oct-185)
  ui/src/lib/api.ts
  ui/src/lib/types.ts
  ui/src/pages/search.tsx
Labels: Fix, ui

#95 First run of review & publish process (oct-181)
  ui/src/components/Publication/Creation/StepFive.tsx
  ui/src/layouts/BuildPublication.tsx
  ui/src/lib/api.ts
  ui/src/pages/publications/[id]/edit.tsx
Labels: enhancement, improvements needed, ui

#100 Update README.md
  README.md
Labels: documentation

#102 Implementing OpenSearch (OCT 183)
  api/endpoints.http
  api/package-lock.json
  api/package.json
  api/prisma/schema.prisma
  api/prisma/seed.ts
  api/serverless.yml
  api/src/components/link/service.ts
  api/src/components/publication/__tests__/createPublication.test.ts
  api/src/components/publication/__tests__/deletePublication.test.ts
  api/src/components/publication/controller.ts
  api/src/components/publication/schema/getAll.ts
  api/src/components/publication/service.ts
  api/src/components/user/service.ts
  api/src/lib/client.ts
  api/src/lib/interface.ts
  api/src/lib/testUtils.ts
  docker-compose.yml
  infra/create-app/main.tf
  infra/create-app/vars.tf
  infra/modules/elasticsearch/main.tf
  infra/modules/elasticsearch/vars.tf
  infra/modules/frontend/main.tf
  ui/src/lib/api.ts
  ui/src/pages/_app.tsx
  ui/src/pages/search.tsx
Labels: bug, enhancement, Fix, api

#104 Creating PDF and JSON icons
  ui/package-lock.json
  ui/package.json
  ui/public/images/json.svg
  ui/public/images/pdf.svg
  ui/public/images/xml.svg
  ui/src/components/Publication/Ratings/index.tsx
Labels: enhancement

#105 Exclude ids from GET /publications
  api/src/components/publication/schema/getAll.ts
  api/src/components/publication/service.ts
  api/src/lib/interface.ts
Labels: enhancement, api

#108 Oct create publication refactor
  api/.env.example
  api/package-lock.json
  api/package.json
  api/prisma/schema.prisma
  api/prisma/seed.ts
  api/serverless.yml
  api/src/components/authorization/controller.ts
  api/src/components/publication/schema/create.ts
  api/src/components/publication/schema/getAll.ts
  api/src/components/publication/service.ts
  api/src/lib/client.ts
  api/src/lib/testUtils.ts
  api/src/utilities/testing.ts
  ui/.gitignore
  ui/lighthouserc.js
  ui/package-lock.json
  ui/package.json
  ui/src/assets/Window.tsx
  ui/src/assets/index.ts
  ui/src/components/Alert/index.tsx
  ui/src/components/CommandPalette/index.tsx
  ui/src/components/EnableDarkMode/index.tsx
  ui/src/components/Header/index.tsx
  ui/src/components/MockupFlow/index.tsx
  ui/src/components/Nav/index.tsx
  ui/src/components/Publication/Creation/LinkToEntry/index.tsx
  ui/src/components/Publication/Creation/StepFive.tsx
  ui/src/components/Publication/Creation/StepFour.tsx
  ui/src/components/Publication/Creation/StepOne.tsx
  ui/src/components/Publication/Creation/StepThree.tsx
  ui/src/components/Publication/Creation/StepTitle.tsx
  ui/src/components/Publication/Creation/StepTwo.tsx
  ui/src/components/Publication/Ratings/index.tsx
  ui/src/components/TextEditor/index.tsx
  ui/src/components/VisualPublicationFlow/index.tsx
  ui/src/components/index.tsx
  ui/src/config/values.ts
  ui/src/layouts/BuildPublication.tsx
  ui/src/lib/api.ts
  ui/src/lib/interfaces.ts
  ui/src/lib/types.ts
  ui/src/pages/browse.tsx
  ui/src/pages/create.tsx
  ui/src/pages/index.tsx
  ui/src/pages/login.tsx
  ui/src/pages/publications/[id]/edit.tsx
  ui/src/pages/publications/[id]/index.tsx
  ui/src/stores/auth.ts
  ui/src/stores/globals.ts
  ui/src/stores/preferences.ts
  ui/src/stores/publicationCreation.ts
  ui/src/styles/globals.css
  ui/tailwind.config.js
Labels: bug, enhancement, setup, Fix, work-in-progress, improvements needed, api, ui
