Repository JiscSD/octopus, pull requests merged in 2022-09, with the labels that each got.

#186 End to end testing
  ui/.env.example
  ui/.gitignore
  ui/README.md
  ui/package-lock.json
  ui/package.json
  ui/playwright.config.ts
  ui/src/__tests__/LoggedIn/browse.e2e.spec.ts
  ui/src/__tests__/LoggedIn/livePublication.e2e.spec.ts
  ui/src/__tests__/LoggedIn/login.e2e.spec.ts
  ui/src/__tests__/LoggedIn/profile.e2e.spec.ts
  ui/src/__tests__/LoggedIn/publish.e2e.spec.ts
  ui/src/__tests__/LoggedIn/search.e2e.spec.ts
  ui/src/__tests__/LoggedOut/browse.e2e.spec.ts
  ui/src/__tests__/LoggedOut/inaccessiblePages.e2e.spec.ts
  ui/src/__tests__/LoggedOut/livePublication.e2e.spec.ts
  ui/src/__tests__/LoggedOut/search.e2e.spec.ts
  ui/src/__tests__/LoggedOut/staticPages.e2e.spec.ts
  ui/src/__tests__/PageModel.ts
  ui/src/__tests__/helpers.ts
  ui/src/components/Nav/Desktop/index.tsx
  ui/src/config/urls.ts
Labels: ui

#237 Unable to publish or preview publications of type "Peer Review" - OCT-377 (BUG)
  ui/src/components/Publication/SidebarCard/Actions/index.tsx
Labels: bug, ui

#236 Generate a unique ID on the frontend and change the logic so references are stored in state on the frontend until a user saves their publication
  api/package.json
  api/prisma/schema.prisma
  api/serverless.yml
  api/src/components/reference/controller.ts
  api/src/components/reference/routes.ts
  api/src/components/reference/schema/create.ts
  api/src/components/reference/schema/index.ts
  api/src/components/reference/schema/update.ts
  api/src/components/reference/schema/updateAll.ts
  api/src/components/reference/service.ts
  api/src/lib/interface.ts
  api/src/middleware/checkOwnership.ts
  api/src/middleware/index.ts
  api/tsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/components/Publication/Creation/MainText.tsx
  ui/src/layouts/BuildPublication.tsx
  ui/src/lib/api.ts
  ui/src/lib/interfaces.ts
  ui/src/pages/publications/[id]/edit.tsx
Labels: api, ui

#243 OCT-354
  .gitignore
  ui/src/components/Publication/Creation/MainText.tsx
  ui/src/components/References/AddReferences.tsx
  ui/src/components/References/EditReferenceModal.tsx
  ui/src/components/References/MenuBar.tsx
  ui/src/components/TextEditor/index.tsx
  ui/src/components/index.tsx
  ui/src/layouts/BuildPublication.tsx
  ui/src/lib/interfaces.ts
Labels: ui

#249 OCT-356 Delete reference (single)
  ui/src/components/Publication/Creation/MainText.tsx
Labels: ui

#246 OCT-355 Add new reference (single)
  ui/src/components/Publication/Creation/MainText.tsx
  ui/src/components/References/EditReferenceModal.tsx
  ui/src/layouts/BuildPublication.tsx
Labels: ui

#251 OCT-338 Pen test: Session Cookie Without Secure Flag
  ui/src/lib/helpers.tsx
Labels: ui

#250 OCT-378 User cannot login if ORCID profile returns nulls for optional fields
  api/src/components/authorization/controller.ts
Labels: bug, api
